version: '3.8'

services:
  data-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8800"       # Mapea el puerto de la aplicación
      - "5050:5005"       # Mapea el puerto de depuración
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/data-service-db
      DEBUG: "true"       # Habilita el modo de depuración
    depends_on:
      - mongo
    entrypoint: ["/docker-entrypoint.sh"] # Usa tu entrypoint configurado

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"     # Mapea el puerto de MongoDB
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
